config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get 'about', to: 'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true, length: {minimum:5, maximum:50}
    validates :body, presence: true, length: {minimum:10, maximum:3000}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer class="pt-2 mt-3 text-muted border-top">
    © 2023
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Emmy's Forum", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
            <li>
              <a class="dropdown-item" href="#"><i class="bi bi-box-arrow-right" style="color: black;"></i> Logout</a>
           </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main class="container">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

<%= link_to "Home", root_path, class: "btn btn-primary" %>

app/views/pages/home.html.erb
<div class="py-4">
    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Emmy's Forum</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <%= link_to "About", about_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mt-4">
  <div class="row">
      <div class="col-md-8 offset-md-2">
          <!-- Form -->
          <form id="blog-form" class="needs-validation" novalidate>
            <div class="mb-3">
                  <%= form.label :title, class: "form-label" %>
                  <%= form.text_field :title, class: "form-control", id: "title" %>
                  <div class="invalid-feedback">
                      Please enter a title.
                  </div>
                </div>
              <div class="mb-3">
                  <label for="category" class="form-label">Category</label>
                  <select class="form-select" id="category" name="category" required>
                      <option value="">Choose a category</option>
                      <option value="Technology">Technology</option>
                      <option value="Business">Business</option>
                      <option value="Lifestyle">Lifestyle</option>
                      <option value="Sports">Sports</option>
                  </select>
                  <div class="invalid-feedback">
                      Please choose a category.
                  </div>
              </div>
              <div class="mb-3">
                  <%= form.label :body, class: "form-label" %>
                  <%= form.text_area :body, class: "form-control", id: "content", name: "content", rows: "10" %>
                  <div class="invalid-feedback">
                      Please enter some content.
                  </div>
              </div>
              <div class="mb-3">
                  <label for="image" class="form-label">Image</label>
                  <input type="file" class="form-control" id="image" name="image" accept="image/*" required>
                  <div class="invalid-feedback">
                      Please upload an image.
                  </div>
              </div>
              <div class="mb-3 form-check">
                  <input type="checkbox" class="form-check-input" id="publish" name="publish">
                  <label class="form-check-label" for="publish">Publish</label>
              </div>
              <%= form.submit class: "btn btn-primary"%>
          </form>
      </div>
    </div>
</div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <h2>
    <%= post.title %>
  </h2>

  <p>
    <%= post.body %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1 style="text-align: center;" class="mt-2">EDIT POST</h1>

<%= render "form", post: @post %>

<br>
<div class="d-grid gap-2 d-md-flex justify-content-md-center">
  <%= link_to "Show this post", @post, class: "btn btn-dark me-md-1" %>
  <%= link_to "Back to posts", posts_path, class: "btn btn-warning" %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<marquee behavior="" direction="">
  <h1>Posts</h1>
</marquee>
<div class="row align-items-md-stretch" id="posts">
  <% @posts.each do |post| %>
    <div class="col-md-6 pt-1">
      <div class="h-100 p-5 text-dark bg-light rounded-3">
        <h2><%= render post %></h2>
        <%= link_to "Show this post", post, class: "btn btn-outline-primary" %>
      </div>
    </div>
  <% end %>
</div>
<%= link_to "New post", new_post_path, class: 'btn btn-primary' %>

app/views/posts/new.html.erb
<h1 style="text-align: center;" class="mt-2">New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: "btn btn-warning" %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%#= render @post %>

<div>
</div>


<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading"><%= @post.title %></h2>
    <p class="lead"><%= @post.body %></p>
    <div class="d-grid gap-2 d-md-block">
      <%= link_to "Edit this post", edit_post_path(@post), class: "btn btn-warning" %>
      <%= link_to "Back to posts", posts_path, class: "btn btn-secondary" %>
    </div>
      <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-sm btn-danger mt-1" %>
  </div>
  <div class="col-md-5">
    <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"></rect><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

  </div>
</div>